version: "3.9"

services:
  api:
    image: your-dockerhub-user/colli-finance-api:latest
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-colli_finance}
      POSTGRES_USER: ${POSTGRES_USER:-colli}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-colli}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-colli} -d ${POSTGRES_DB:-colli_finance}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

volumes:
  postgres_data:
