services:
  uploads-init:
    image: busybox
    user: root
    command: sh -c "chown -R ${UID:-1000}:${GID:-1000} /app/uploads || true"
    volumes:
      - uploads_data:/app/uploads
    restart: "no"

  api:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: colli-finance-api       
    image: colli-finance-api:local
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      uploads-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-colli_finance}
      POSTGRES_USER: ${POSTGRES_USER:-colli}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-colli}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-colli} -d ${POSTGRES_DB:-colli_finance}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
  uploads_data:
